trigger:
- main

pool: myAgentPool

variables:
  azureServiceConnectionId: 'myServiceConnection'
  webAppName: 'ajay-flask-ml-webapp'
  environmentName: 'ajay-flask-ml-webapp'
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    pool: myAgentPool
    steps:    
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'

    - script: |
        make setup
        source ~/.azure-devops-cicd-pipeline/bin/activate
        make install
        make lint
        make test
      workingDirectory: $(projectRoot)
      displayName: 'Run install, lint, and tests'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Publish artifact'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: myAgentPool
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip